# Generated by Django 4.0 on 2021-12-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Book'},
        ),
        migrations.AlterField(
            model_name='books',
            name='Publication_date',
            field=models.DateField(),
        ),
    ]
