# Generated by Django 4.0 on 2021-12-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_books_options_alter_books_publication_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
